In [ ]:
A

1

In [ ]:
A = 1

In [ ]:
print(A)

1


#Markdown

## MK pengantar sains data

### Nama: Satria Ramadhani



Perkenalan Google Colab

In [1]:
nama = "Amar"
print(nama)

Amar


---

In [ ]:
umur = "18" #ini adalah text

In [ ]:
print(umur)

18


In [ ]:
print(umur+umur)

1818


In [ ]:
umur = 18 #18 adalah angka

In [ ]:
print(umur*2)

36


---

In [ ]:
age = 18 #+15

In [ ]:
print(age)

18


---

In [ ]:
Nilai_Matematika = [70,80,75,90,85]
print(Nilai_Matematika)

[70, 80, 75, 90, 85]


In [ ]:
# Nilai_Matematika adalah variabel
# [70,80,75,90,85] adalah value

In [ ]:
Nilai_Matematika[1]

80

In [ ]:
Nilai_Matematika[0]

70

In [ ]:
len(Nilai_Matematika) #panjang data

5

In [ ]:
sum(Nilai_Matematika)

400

In [ ]:
sum(Nilai_Matematika)/len(Nilai_Matematika)

80.0

---

In [ ]:
#library adalah pustaka. modul adalah isian dari pustaka
import numpy as np

In [ ]:
Nilai_Matematika = np.array([70,80,75,90,85])

In [ ]:
Nilai_Matematika

array([70, 80, 75, 90, 85])

In [ ]:
print(np.mean(Nilai_Matematika))

80.0


In [ ]:
print(np.std(Nilai_Matematika))
print(np.min(Nilai_Matematika))
print(np.max(Nilai_Matematika))
print(np.sum(Nilai_Matematika))

7.0710678118654755
70
90
400


---

In [ ]:
#kita akan membuat populasi 1000 mahasiswa
#dengan metode distribusi normal yang random
#dengan rata rata 70
#dengan standar deviasi adalah 10
#dengan kode random 123

np.random.seed(123)

populasi= np.random.normal(
    loc= 70,
    scale= 10,
    size= 1000

)

populasi

array([ 59.14369397,  79.97345447,  72.82978498,  54.93705286,
        64.21399748,  86.51436537,  45.73320757,  65.71087371,
        82.65936259,  61.33259598,  63.21113848,  69.05291031,
        84.91389626,  63.61098003,  65.5601804 ,  65.65648724,
        92.05930083,  91.86786089,  80.04053898,  73.86186399,
        77.37368576,  84.90732028,  60.64166132,  81.75829045,
        57.46119332,  63.62248498,  79.07105196,  55.713193  ,
        68.5993128 ,  61.38245104,  67.44380629,  42.01410895,
        52.28466895,  63.00122765,  79.27462432,  68.26364317,
        70.02845916,  76.88222711,  61.20463657,  72.83627324,
        61.94633482,  52.72330506,  66.09100206,  75.73805862,
        73.38589051,  69.88169506,  93.92365266,  74.1291216 ,
        79.78736006,  92.38143338,  57.05914677,  59.6121179 ,
        87.43712225,  62.01937265,  70.2968323 ,  80.69315969,
        78.90706391,  87.54886182,  84.95644137,  80.6939267 ,
        62.27291286,  77.94862668,  73.14271995,  56.73

---

In [ ]:
#random sampling
sampel = np.random.choice(
    populasi,
    size= 30,
    replace= False

)

sampel

array([54.69487103, 69.37601451, 81.06266658, 63.17549066, 71.60293721,
       67.66496007, 81.78057004, 67.79707535, 54.31559953, 80.69315969,
       89.84582398, 63.7597515 , 77.47392962, 71.45979225, 66.20269672,
       79.33585094, 66.75764652, 66.41979897, 62.67538013, 66.24441881,
       72.90874387, 56.94214134, 64.1814979 , 70.79227014, 81.61068358,
       59.14097599, 79.93806707, 87.85168814, 77.74000002, 75.81589803])

In [ ]:
np.mean(populasi)


np.float64(69.60435863919207)

In [ ]:
np.mean(sampel)

np.float64(70.97534667307986)

---

In [ ]:
sampel_acak = np.random.choice(
    populasi,
    size=50,
    replace=True

)

sampel_acak

array([70.68788333, 52.72330506, 68.31573568, 87.15468592, 70.58687438,
       74.16123814, 62.73885972, 76.3048803 , 76.80071533, 66.27728269,
       52.44598155, 70.29642925, 83.40098704, 79.7364438 , 95.59850231,
       69.93692749, 51.69333638, 55.27022391, 81.75910772, 47.6358265 ,
       72.43765761, 77.60949393, 51.1150762 , 81.61068358, 70.72907243,
       74.74347298, 78.07236535, 73.00846402, 70.45490081, 66.01376075,
       66.52035662, 80.14303884, 76.34763132, 62.2422998 , 73.51679372,
       59.60895617, 67.87919878, 79.37850297, 68.78551325, 72.87214281,
       76.00882509, 63.30897374, 87.84356795, 66.68871702, 73.43257981,
       57.0289998 , 63.24530566, 77.0497948 , 70.47341881, 69.01315303])

In [ ]:
#bias
sampel_bias = populasi[populasi > 80][:50]
print("populasi :", np.mean(populasi))
print("random :", np.mean(sampel_acak))
print("bias:", np.mean(sampel_bias))


populasi : 69.60435863919207
random : 70.41415888245456
bias: 85.43686324883856
